### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by rmasoni** [theripper93/hurry-up#1]
Hey, great job on the module! I have a few suggestions:

- Option to only play sounds to players, not the DM.
- Smart snapping into place like Small Time (would be extra great if it could snap _to_ or on top of Small Time and start at this default position for everyone).
- Maybe the progress bar could be more visible and appear above or below the numbers instead of behind them. Maybe have a toggle for its visibility as well.
- Give a bit more padding around the numbers, make them slightly smaller (mockup below).

<img width="230" alt="image" src="https://user-images.githubusercontent.com/62244/132079992-06c11db1-4717-4260-bf36-4d93c3d6b6c2.png">

**Comment by theripper93** [comment]
Ill take them into consideration but I plan on keeping it simple , I have a lot of modules to maintain ;)

**Comment by rmasoni** [comment]
Cool, thanks! Most of them are QoL, but I think playing sounds only to players is a must-have.

**Comment by theripper93** [comment]
if you are gonna make your players suffer the ticking, you should suffer it as well

**Comment by rmasoni** [comment]
To each their own suffering for taking too long! ⏳
