### ISSUE TITLE
Timer never start for SWADE system

### ISSUE THREAD

**Issue by Lifthraser** [theripper93/hurry-up#12]
Hello, the module recognise combat, know when it's a npc or a player and display timer accordingly, this works fine. 
But the timer never starts.
Tested with only this module and socketlib actiivated.

**Comment by theripper93** [comment]
Did you unpause the game

**Comment by Lifthraser** [comment]
I am deeply ashamed. sorry.
I'll use this moment to thanks you a million times for all your paid and free modules.
