### ISSUE TITLE
Suggestion: Change Location It Pops Up

### ISSUE THREAD

**Issue by kunsumii** [theripper93/hurry-up#14]
In the module configuration settings, can we get an option to make this timer popup from Topleft, TopRight, Bottomleft, & BottomRight?

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
