### ISSUE TITLE
Destroy a timer

### ISSUE THREAD

**Issue by Stratlin** [theripper93/hurry-up#3]
Is there a way to pause/disable/destroy a timer? If not, it would be a great option to have. Thinking of use cases like if the walls are closing in and they solve the puzzle but there's 2 minutes left on the clock, etc. 

Thanks for the great mod.

**Comment by theripper93** [comment]
that is not in my plans now (and probably for the future) this is a "Combat" timer, the fact that you can create a timer via macro is just an extra but it's not made for that (also you can close the timer with ESC)
